### ISSUE TITLE
为什么Refresh设置成true，watcher还是收到通知了

### ISSUE THREAD

**Issue by liyue201** [wothing/wonaming#9]
setopt := &etcd.SetOptions{TTL: time.Duration(ttl) * time.Second, PrevExist: etcd.PrevExist, Dir: true, Refresh: true}

**Comment by elvizlai** [comment]
Please provide the version of etcd.

I updated example, please try and feedback.

**Comment by liyue201** [comment]
果然是版本太老了，thx
